server:
  port: 8090
spring:
  application:
    name: spring-boot-flyway
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:dev}
    password: ${SPRING_DATASOURCE_PASSWORD:qwerty}
    url:  ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bookdb}
    hikari:
      poolName: Hikari
      auto-commit: false
  flyway:
    enabled: true #Enables or disables Flyway's migration functionality for your application
    locations: classpath:db/migration #Specifies the locations of migration scripts within your project.
    validate-on-migrate: true #Flyway will validate the applied migrations against the migration scripts every time it runs a migration.



